sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-150
env:
  global:
    -
      # LTD_AWS_ID
      secure: P81FIY2D6ovjaFeCO1NOtvD6yQXpElr7wbSlteMXMSh1jx/zjvuxLL5yAeu0+JrWWBK39SBtagbKA1TzRtzJ0yiyuWoi498Bhd+ONiOr1ine6/f5nBCaj97PmkQBWDukmYQygKUn2cU28WMNQmlYla3CCXJa1Fp+JFrZd1iWKqodhKCEzZocFh5IwZ5xQb5FR/cSZu0QhedkJCpiP1mkhEqFx8VOrLJAUb8RcYaYFjIzQ1srLtCHTNTy7cd3dgYRMkoPvuOsXt/Tf7Vs/Yj6MVTDwDvRN539Oef/D/eGEcw20yzQENK7gVIDB3eOsPYSNnH+Q96ZkBqGetVsP/z49oT9HeBiSnyrV5qP2u8wYtCDGWwnbEr4dHr1t1TfQ6LpIbzG8vgBEOv3Vxdac+tEBylOp8CPuUd1C/HD5o/HGpj7GZDBxxp2LbXWA+rlx8w8iVgqbBXEOOnpyv5mpWkkaM44xkOyVtzjh6pPTHZJ8S9HlwF9dgncOTPRZeVcMbxbJ3Q7ortC1LbIJ0wXWAwZMH4ra9jsVWlH1qusqwB5A6EhPKfL0F7nRzVl4GfjJAbsTVZmUZgU1d3doPKPjn7OTzknSVDO6ohLSscu+IjAzWgpY2nDRwXx/nVWKAczwmr0MvZQW7sSKIuJqtL4rz5jwEIPGb6CTYTNcUUEUznZVcc=
    -
      # LTD_AWS_SECRET
      secure: GO31iAmW9LBio0hLGgIlHj/kX1uBUvs0H30XYTnb3AluKTFjUb4oz0J3BTVUk2MMiMkT3iFveQWnxUPqKF3f4zF4Y/p+l10C5RZHzyqNKfFf+qNtTZBldZx0LWZgxmFRBsRik3m25mlHv1lTp7TUDfUZMn6beMCD9mf3rbsNWPu2r5xtueTJ2SZlQolQ/xAI9vTUtM3wf7sYe/NbR+Jk94RLT28TRLalp+xxH+/x6CO4iuS8djUQ1e6IJhFY+C0tI1wwI/PUK3M2UFKVQBJQiaIjxMMfKziu54uCutGuxC3qyVVXWocRh2uA8n/g6P7lRQKA5c8COmkREPIqGRcI0533rwNtUOZqlbf5xSeG40FpjAAHe4Cr+k+DB9iwXFl1+x/Zr1MJM9ZoA4WDawyGe2p3fnvh9w7atB5IW45OMpn7riZGU3R80maEZrSoRoseSEctmdLG40yFY3lbSmwxyoZ4TEPS9Gq6u8h41RtMBAO3H4gog5dmpx8anrDYnIvgokR1VHNfq4KXUm/HX2XMrSOlRF3aLPk8hGf/JslsQi/cn4pqX4FZnzSPJ9d3pkdoLvVGMPH99o+jY6cX+8teX4+xZpZ4FOkcyrhOyBq+yBZuGStqNR/z65Sectv834mJBDdVz33MwWJ28uU6YtVDf0a+EkrfqaN40Ci8rGShBQk=
    -
      # LTD_USERNAME
      secure: cZ8X5yvD/+xIgCOn5+Rz5Plwf57qfzreOo/ahYqgphr2PWVA8QhsTe4Owr4zhMpwylMO0q1l9uFaAVp0yI1aW5+rb+WryOvh3Cz4jbAGobSXh8bbIaW7P9HRfo0ofjySZC6j4WiluVmEn5xYS6Noa0iHjCYsxD471WKoMDIseQwja6KAkPoKURs68Un8CrxD7O1GeOPA1uVUy9LqaW+KjvxFy9HzwjiwdWeduw0ndQxX/U/ffSPDqaYppI+Yza4FLlhVMgiRSpgGptD35HbMJ11h/M0fxag2VRSreEbjQ2PGbLQ9WfryustCf6vHO8CgfPbmp6GLPpxg11Tk61v+a9K0pZPmqfo0nkecFT8nGir8HT2uWcni63g/0y2zbgQ+Q+5d5+SkMyDFv2mwaTE6at5EdWNkpd74QjEEIggyIX+tjoM00Z3kOWQfZP6ZuBnhNPr0WmBCfvjV1NZLm5WQAhqAe3KbzNyX7QyUmYpa3gbccxzxFbP2iSvbPVHh05UOq50h6c041rwiF9BU3nEz1a7JZNf9a5e8egZafOn7sK9KPTN/5OAfY6iLLYWh0VRhRVjxt9SsfG/lAskbMpwiOEPLZ6U55YusdJDC7gLBqhmw2GBMDOu18jdvREzOfcVH3i6LyWSgBObdem4k0BW+TxeiGTmmi5gmttvpb03liEc=
    -
      # LTD_PASSWORD
      secure: pnpomnSsKXhuZ2XK26+bxC8fskthRwhM7Lqclqov5J6DFk/1kyzVFcczmmtcKxYqyKHnm8inV2cOPhr7P90qHs+wgIyZDe8wKevhzpLdCkxDw8/t17EbW4LVPKJTjaKhYW75YxLSXzBYxO3BNOIRV6AD/8DWbTK/k5mbYT1uVgMqGBuYwpoVHotgs7wv6nm0AmpJQQG+tRiBm2UGMwVCvd1T9DnsgCFNbT5IWTlg9Q45k8/ghx+v9von9mOc4kVmFb56jrsKYzabyh5M4MEYUjuz0GHuB6DvQ1KLtsEzlHT200HVnw063KyFnpp+hyPp+gNKWWCekI4CSyEYHTvMCkLdZZzbCBV4eeiiy33rYbfN5wLVBNK0BlpmAa35Hl3i5yqyR06uZsdK8elHqbts5CM902FMhyqqYMb0v7XDHQiavEmBFZ4ozOqNneNiihkl0chjME4gb/hgOUOeoorrzJhR09nmuz0cYy6Uz9if5DElMwl0vYH8XLAONuawi3fER1XBmzz11zUc7G78Vu7XmuZt207epcJKw5HD91XUy9e82fJ+BNk7kSwS4Vt8hGV1oJH7F+0fjEt+lqYfBQmXTCQLXu56wckwPo+gtXQ6VF1mOHBa1iuiGCngVQiIz3xJWJUye6VM1kaDHK+yhIgohaJNFOVYegyLbKtV32OjrAc=
